<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tenda Glamping naturehike village 13 original</name>
   <tag></tag>
   <elementGuidId>662b5740-80a4-4146-9b1d-b361d379b4d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Tenda Glamping naturehike village 13 original no blackdog minimal work brocklyn arpenaz coody dhaulagiri altrek mounthikerRp7.000.000JANGEK OUTDOOR EQUIPMENTKab. Bantul' or . = 'Tenda Glamping naturehike village 13 original no blackdog minimal work brocklyn arpenaz coody dhaulagiri altrek mounthikerRp7.000.000JANGEK OUTDOOR EQUIPMENTKab. Bantul')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[3]/div/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3e6601be-36fa-4c16-9ed6-5082ab2d779b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bYD8FcVCFyOBiVyITwDj1Q==</value>
      <webElementGuid>787ad7b0-55ae-432d-bf68-d8e3f6f78e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tenda Glamping naturehike village 13 original no blackdog minimal work brocklyn arpenaz coody dhaulagiri altrek mounthikerRp7.000.000JANGEK OUTDOOR EQUIPMENTKab. Bantul</value>
      <webElementGuid>c2244dc8-94c9-4f27-9cf4-5b094c7e6305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[3]/div[@class=&quot;css-jza1fo&quot;]/div[@class=&quot;css-5wh65g&quot;]/a[@class=&quot;oQ94Awb6LlTiGByQZo8Lyw== IM26HEnTb-krJayD-R0OHw==&quot;]/div[@class=&quot;bYD8FcVCFyOBiVyITwDj1Q==&quot;]</value>
      <webElementGuid>162fa53e-9d7a-46b0-8935-09df720edd20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[3]/div/div/a/div</value>
      <webElementGuid>bc98ecfd-184f-4863-a37f-f5cbde9a7b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urutkan:'])[1]/following::div[6]</value>
      <webElementGuid>241c4ee1-c466-45db-aa82-7be9023c9241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>1c5b546c-189f-4b1e-a303-aa66d7bc7a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tenda Glamping naturehike village 13 original no blackdog minimal work brocklyn arpenaz coody dhaulagiri altrek mounthikerRp7.000.000JANGEK OUTDOOR EQUIPMENTKab. Bantul' or . = 'Tenda Glamping naturehike village 13 original no blackdog minimal work brocklyn arpenaz coody dhaulagiri altrek mounthikerRp7.000.000JANGEK OUTDOOR EQUIPMENTKab. Bantul')]</value>
      <webElementGuid>9b7ab243-bb94-46c7-8910-b263735a54b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
