<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_TENDA VILLAGE 13  GLAMPING  TENDA OTOMATIS NATUREHIKE CNH22ZP004 - MATRAS</name>
   <tag></tag>
   <elementGuidId>ee2f83b2-e4c4-484c-9e9e-77a1ae82a0d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.css-j63za0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'TENDA VILLAGE 13 / GLAMPING / TENDA OTOMATIS NATUREHIKE CNH22ZP004 - MATRAS' or . = 'TENDA VILLAGE 13 / GLAMPING / TENDA OTOMATIS NATUREHIKE CNH22ZP004 - MATRAS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c629a426-9662-4858-b854-36d678cbef2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6d48fbdb-791d-46c5-80d8-decf9b2d1330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-j63za0</value>
      <webElementGuid>7cf69697-4293-4d09-a800-ae7e0ecc0bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lblPDPDetailProductName</value>
      <webElementGuid>abd26c31-ba16-4338-a266-416f12d1752e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TENDA VILLAGE 13 / GLAMPING / TENDA OTOMATIS NATUREHIKE CNH22ZP004 - MATRAS</value>
      <webElementGuid>b2e330e9-4b57-4bdc-9773-57fd3c6e58b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-product_content&quot;)/div[@class=&quot;css-jmbq56&quot;]/div[@class=&quot;css-1nylpq2&quot;]/h1[@class=&quot;css-j63za0&quot;]</value>
      <webElementGuid>edfae0b0-211b-49e4-a79b-2a4c3e851e42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      <webElementGuid>646e9308-3978-4867-91dd-75da2860d43b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::h1[1]</value>
      <webElementGuid>3351aea0-7d26-4469-9a04-295ff696736c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/following::h1[1]</value>
      <webElementGuid>0bad4d2e-95b4-4b54-b8aa-c3bccfcf8357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terjual'])[1]/preceding::h1[1]</value>
      <webElementGuid>85800e33-b87e-4879-bcc8-177659ca0565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bintang'])[1]/preceding::h1[1]</value>
      <webElementGuid>18650901-7206-46b7-8bfd-f0aa398cc5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>a85032b4-d06d-47e8-b929-96f48ae217c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'TENDA VILLAGE 13 / GLAMPING / TENDA OTOMATIS NATUREHIKE CNH22ZP004 - MATRAS' or . = 'TENDA VILLAGE 13 / GLAMPING / TENDA OTOMATIS NATUREHIKE CNH22ZP004 - MATRAS')]</value>
      <webElementGuid>219f2d5d-c896-4c27-a361-1762195256d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
