<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_WhatsApp ke 628995324319</name>
   <tag></tag>
   <elementGuidId>6c8b6893-31ab-4534-932c-2be3fd4ead55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'WhatsApp ke 628995324319' or . = 'WhatsApp ke 628995324319')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'WhatsApp ke 628995324319' or . = 'WhatsApp ke 628995324319')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-kdt10q</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>81e76e0d-8aa0-4d4b-b61f-aad6742acf59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>whatsapp</value>
      <webElementGuid>e6a3c957-b6ac-4658-b91a-7f3e6920fc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kdt10q</value>
      <webElementGuid>faba3067-c255-4616-acc3-f2c7b1b27f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WhatsApp ke 628995324319</value>
      <webElementGuid>041f6f3b-cfd3-43f3-b6e4-1689b5270dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__skipper&quot;)/div[@class=&quot;css-b1khel&quot;]/div[@class=&quot;css-kqvkc7&quot;]/div[@class=&quot;css-1akx9dq&quot;]/div[@class=&quot;css-rrvbed&quot;]/div[@class=&quot;css-j5mr2z&quot;]/div[@class=&quot;css-1ogrxxd&quot;]/div[@class=&quot;css-kdt10q&quot;]</value>
      <webElementGuid>6bd4c968-a8bb-4fe5-88d7-541f64076cd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__skipper']/div/div/div/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>6f749b57-600e-4087-aa7b-648cec1957f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Metode Verifikasi'])[1]/following::div[3]</value>
      <webElementGuid>b9cca4c8-3d94-4668-9c2b-89e617ee2619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMS ke'])[1]/preceding::div[2]</value>
      <webElementGuid>6e961952-ab44-44fb-9adc-8d37b056114a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div</value>
      <webElementGuid>c014bfd8-1ea7-401c-ab6e-488fd1bbb2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'WhatsApp ke 628995324319' or . = 'WhatsApp ke 628995324319')]</value>
      <webElementGuid>17b5c6de-ea6b-4f9b-b2a4-ce836f707fb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
