<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Kamera Analog_css-1ckwll6</name>
   <tag></tag>
   <elementGuidId>4a6cdf85-09dd-41af-8b29-f8b46d308095</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[3]/div/div/div[4]/ul/li/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>75f52594-833a-4e80-853c-035f7ba5704c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://p16-assets-sg.tokopedia-static.net/tos-alisg-i-cqp9s0kcd0-sg/assets-tokopedia-lite/v2/zeus/kratos/9cf5645b.svg</value>
      <webElementGuid>02838774-94eb-44e0-8ea9-eb8c935a52c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1ckwll6</value>
      <webElementGuid>5fe00aaa-48ff-4c6b-a65a-865e3ad4b516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>arrow icon</value>
      <webElementGuid>997e22d3-86cf-4430-8043-81ccc1d52f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>ddlCL3CategoryLevel3kamera-analog</value>
      <webElementGuid>5d74db19-695d-4535-be9b-7d6c33c27eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[2]/div[@class=&quot;css-gvsi1m e1nlzfl0&quot;]/div[@class=&quot;css-1xpribl e1nlzfl3&quot;]/div[@class=&quot;css-1mvy9n0 e1nlzfl4&quot;]/div[@class=&quot;css-18p2ktc&quot;]/div[@class=&quot;css-ufscxh&quot;]/div[2]/div[@class=&quot;filterBlockContainer css-rk97m8&quot;]/div[@class=&quot;filterOption css-ohkxpv css-vevvmu&quot;]/div[@class=&quot;css-gvoll6&quot;]/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-eicyaz&quot;]/ul[@class=&quot;css-ntfpy7&quot;]/li[@class=&quot;css-zxgmc8&quot;]/img[@class=&quot;css-1ckwll6&quot;]</value>
      <webElementGuid>bc9f3a00-8489-4d43-8ea6-994326cc972c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[3]/div/div/div[4]/ul/li/img</value>
      <webElementGuid>673f3962-2a3e-44fe-8c31-12153f2e8425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='arrow icon'])[4]</value>
      <webElementGuid>5a13c50f-a234-477e-a424-146f549c59d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/img</value>
      <webElementGuid>b5344d12-2dd6-479b-8733-fb88216440eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://p16-assets-sg.tokopedia-static.net/tos-alisg-i-cqp9s0kcd0-sg/assets-tokopedia-lite/v2/zeus/kratos/9cf5645b.svg' and @alt = 'arrow icon']</value>
      <webElementGuid>f556bbbf-2d90-4011-96e4-c3faed2ea96b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
