<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_tenda ALTREK</name>
   <tag></tag>
   <elementGuidId>3c74db95-1f84-4f00-a75b-0c5c9d034a25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'tenda ALTREK' or . = 'tenda ALTREK')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-main-wrapper']/div[2]/div[2]/div[3]/a[10]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>84dd316c-3323-412a-872e-9828be2869fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1bwqzep</value>
      <webElementGuid>39556967-718f-4618-a459-75b80d975e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tenda ALTREK</value>
      <webElementGuid>65c022af-3e62-49a7-8d99-9650ce577f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-main-wrapper&quot;)/div[@class=&quot;css-12jp264 e90swyx2&quot;]/div[@class=&quot;css-nlrenb&quot;]/div[@class=&quot;css-1471acr&quot;]/a[@class=&quot;css-muuo1g&quot;]/div[@class=&quot;css-1bwqzep&quot;]</value>
      <webElementGuid>230dbb33-4503-4382-bf7a-7d0f740635df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-main-wrapper']/div[2]/div[2]/div[3]/a[10]/div[2]</value>
      <webElementGuid>b9a5125d-ae1b-4e4c-9da4-5e29e74297d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tenda dom altrek'])[1]/following::div[2]</value>
      <webElementGuid>513036ae-8996-4231-87be-79aa33556e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tenda altrek'])[7]/following::div[4]</value>
      <webElementGuid>63ae6539-8e90-4d2a-a460-ebf79655ea17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::div[4]</value>
      <webElementGuid>07eac767-ccf1-43ea-b168-f9fcf320bc9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[10]/div[2]</value>
      <webElementGuid>d9bf3c21-4b74-41b4-ac99-ebbfe226809e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'tenda ALTREK' or . = 'tenda ALTREK')]</value>
      <webElementGuid>fb85549b-92b6-4334-a22d-cc82fe047afd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
