<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_DJI Pocket 3 Creator Combo Garansi TAM Official 1 Tahun Resmi Osmo Pocket 3 - Creator Combo - Extreme Pro 512</name>
   <tag></tag>
   <elementGuidId>9a014806-e517-4082-8792-02988f6f1b8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.css-j63za0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5aaab166-f3a2-402c-8291-98de0a41cdd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1431823e-824f-46a9-991a-c85b14ba45cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-j63za0</value>
      <webElementGuid>f4d9bb41-0b8e-4510-bd76-bb2dc48b4a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lblPDPDetailProductName</value>
      <webElementGuid>a8dea13c-ba73-4585-9e36-4f4f10658080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DJI Pocket 3 Creator Combo Garansi TAM Official 1 Tahun Resmi Osmo Pocket 3 - Creator Combo - Extreme Pro 512</value>
      <webElementGuid>112373f3-16ee-4142-afbd-ebb24f5f4726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-product_content&quot;)/div[@class=&quot;css-jmbq56&quot;]/div[@class=&quot;css-1nylpq2&quot;]/h1[@class=&quot;css-j63za0&quot;]</value>
      <webElementGuid>79313f91-829e-4266-8fa1-bcb02b57c12b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      <webElementGuid>24b4f9c5-17d2-416a-8507-c7730a1f028f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::h1[1]</value>
      <webElementGuid>acfc4c10-650c-4575-8492-f0db4e6f0aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/following::h1[1]</value>
      <webElementGuid>c3aa748e-a8af-4f49-84e9-60bf7269f04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terjual'])[1]/preceding::h1[1]</value>
      <webElementGuid>8117dd96-d1dd-4688-83ed-eac35b3d99f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bintang'])[1]/preceding::h1[1]</value>
      <webElementGuid>42c70eae-af5a-4ce6-a27e-6a7efbe7b7ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>26536660-d29e-4084-93a9-3b138f6eb3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'DJI Pocket 3 Creator Combo Garansi TAM Official 1 Tahun Resmi Osmo Pocket 3 - Creator Combo - Extreme Pro 512' or . = 'DJI Pocket 3 Creator Combo Garansi TAM Official 1 Tahun Resmi Osmo Pocket 3 - Creator Combo - Extreme Pro 512')]</value>
      <webElementGuid>7fef57fb-5b95-48ea-bb02-0ef5acd0e64e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
