<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Kamera Digital_css-1ckwll6</name>
   <tag></tag>
   <elementGuidId>8d5811c4-abd4-4ed0-b17b-ce08ee6d340b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[3]/div/div/div[5]/ul/li/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d12d6ef8-1307-4813-8fc2-6a7bee697006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://p16-assets-sg.tokopedia-static.net/tos-alisg-i-cqp9s0kcd0-sg/assets-tokopedia-lite/v2/zeus/kratos/9cf5645b.svg</value>
      <webElementGuid>ff217e31-126a-4d57-958d-f236b9798dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1ckwll6</value>
      <webElementGuid>706edd42-720d-4462-bdcc-bd3d1494ea7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>arrow icon</value>
      <webElementGuid>6603ca54-fdbf-4d97-b783-3a3cbef0afe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>ddlCL3CategoryLevel3kamera-digital</value>
      <webElementGuid>82c33dc8-46f2-4960-902e-311eac0f23cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[2]/div[@class=&quot;css-gvsi1m e1nlzfl0&quot;]/div[@class=&quot;css-1xpribl e1nlzfl3&quot;]/div[@class=&quot;css-1mvy9n0 e1nlzfl4&quot;]/div[@class=&quot;css-18p2ktc&quot;]/div[@class=&quot;css-ufscxh&quot;]/div[2]/div[@class=&quot;filterBlockContainer css-rk97m8&quot;]/div[@class=&quot;filterOption css-ohkxpv css-vevvmu&quot;]/div[@class=&quot;css-gvoll6&quot;]/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-eicyaz&quot;]/ul[@class=&quot;css-ntfpy7&quot;]/li[@class=&quot;css-zxgmc8&quot;]/img[@class=&quot;css-1ckwll6&quot;]</value>
      <webElementGuid>b28d83f2-e324-4159-8181-4b23af9b4a56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[3]/div/div/div[5]/ul/li/img</value>
      <webElementGuid>617e9f6c-be34-4941-9b25-1a15646e3155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='arrow icon'])[5]</value>
      <webElementGuid>3814ec34-c4fe-4f78-84bb-601a47432c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ul/li/img</value>
      <webElementGuid>18f4a3d5-aa69-4d82-b00e-7ca418c8baf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://p16-assets-sg.tokopedia-static.net/tos-alisg-i-cqp9s0kcd0-sg/assets-tokopedia-lite/v2/zeus/kratos/9cf5645b.svg' and @alt = 'arrow icon']</value>
      <webElementGuid>6f7d6c8f-b2bf-4b69-a25f-30c97b142207</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
