<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nomor HP sudah terdaftarMasuk dengan nomor ini 089611515526MasukUbah</name>
   <tag></tag>
   <elementGuidId>8b03eba4-c0df-43cb-8fe3-7362fb64fb2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Nomor HP sudah terdaftarMasuk dengan nomor ini 089611515526?MasukUbah' or . = 'Nomor HP sudah terdaftarMasuk dengan nomor ini 089611515526?MasukUbah')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-19npxxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Nomor HP sudah terdaftarMasuk dengan nomor ini 089611515526?MasukUbah' or . = 'Nomor HP sudah terdaftarMasuk dengan nomor ini 089611515526?MasukUbah')]s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>165696ca-0f4c-4126-85d2-66c08bafbaa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-19npxxt</value>
      <webElementGuid>5a5d2422-dccc-417c-a21f-3d6bb4771f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nomor HP sudah terdaftarMasuk dengan nomor ini 089611515526?MasukUbah</value>
      <webElementGuid>ee3941b9-cc4d-445a-80c1-dfb1b07a45a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;css-1umf4fo&quot;]/div[@class=&quot;css-1ar5wm2&quot;]/div[@class=&quot;css-19npxxt&quot;]</value>
      <webElementGuid>a47928e6-eda7-461b-be24-b01f8383a158</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[4]</value>
      <webElementGuid>809f438f-9893-4f7b-b6a1-6c2e2e8a8392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>676a696e-4bad-4cf5-aac6-891c3fda06d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Nomor HP sudah terdaftarMasuk dengan nomor ini 089611515526?MasukUbah' or . = 'Nomor HP sudah terdaftarMasuk dengan nomor ini 089611515526?MasukUbah')]</value>
      <webElementGuid>43faf068-8dea-450e-85f2-c9e5e6a45374</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
