<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Urutkan_Q6EyY3lHkLBxLWawflt9Sg NWVIhquIvF0Jc0Qlizjluw</name>
   <tag></tag>
   <elementGuidId>40048ad5-d0d3-4b30-9149-ac9367728c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[3]/div/div/a/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d088fe1e-4ef9-4916-8b78-1741c3b40297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>product-image</value>
      <webElementGuid>5f55f651-a4dc-49a9-86ca-484064789174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.tokopedia.net/img/cache/200-square/VqbcmM/2023/1/20/93f7a13d-3a7e-402b-9377-ca38a56259c5.jpg.webp?ect=4g</value>
      <webElementGuid>57ece099-ea38-4a09-94dc-92795186e85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Q6EyY3lHkLBxLWawflt9Sg== NWVIhquIvF0Jc0Qlizjluw==</value>
      <webElementGuid>5b5fe884-23ab-4725-9caf-c0f0bc70fc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>3708f5de-371a-47d5-82fb-2a3dda2c64ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>ef1ee3bc-ff4a-468e-8c4c-6993cff78670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[3]/div[@class=&quot;css-jza1fo&quot;]/div[@class=&quot;css-5wh65g&quot;]/a[@class=&quot;oQ94Awb6LlTiGByQZo8Lyw== IM26HEnTb-krJayD-R0OHw==&quot;]/div[@class=&quot;bYD8FcVCFyOBiVyITwDj1Q==&quot;]/div[@class=&quot;FsRHU-HdyqHfg3GrIQNUWA==&quot;]/div[@class=&quot;Het-JIVjmDQQceOwOkdz3A==&quot;]/div[@class=&quot;BOTtfV+a1h02dbfq5FFGFw== responsive EXUyQTyJzTrmf3n3cdbJjA==&quot;]/img[@class=&quot;Q6EyY3lHkLBxLWawflt9Sg== NWVIhquIvF0Jc0Qlizjluw==&quot;]</value>
      <webElementGuid>011387e4-6a2a-4b25-b646-b14f9b745e33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[3]/div/div/a/div/div/div/div/img</value>
      <webElementGuid>ffdd4725-c06a-41ff-a191-19b2bfe73056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='product-image']</value>
      <webElementGuid>6688e8b0-0686-4674-94c5-59a9eee61a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>2f9d9229-3bbf-4805-82b0-2ecd5d4bffcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'product-image' and @src = 'https://images.tokopedia.net/img/cache/200-square/VqbcmM/2023/1/20/93f7a13d-3a7e-402b-9377-ca38a56259c5.jpg.webp?ect=4g']</value>
      <webElementGuid>e922756a-a653-42ca-9897-7397f2bad507</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
