<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Urutkan_H078hzBk9mrpZdtHF5MqWA wSt-NCwsL186UdS6D-IpAg</name>
   <tag></tag>
   <elementGuidId>f2f5f391-c68f-4ff2-9a5b-d61c06dc97fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[3]/div/div/div/a/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9539ef19-fd18-44fa-ac27-842967048496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>product-image</value>
      <webElementGuid>47f9c00f-d808-4df7-a414-b4ba9637d705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.tokopedia.net/img/cache/200-square/VqbcmM/2023/1/20/93f7a13d-3a7e-402b-9377-ca38a56259c5.jpg.webp?ect=4g</value>
      <webElementGuid>2a7341bb-02a5-49e3-beaf-196d6c4c4d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>H078hzBk9mrpZdtHF5MqWA== wSt-NCwsL186UdS6D-IpAg==</value>
      <webElementGuid>307b6c55-6b9e-4de5-8c22-084e59a00952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>373ffc23-8bc8-4e26-8964-077e1dbb8a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>2e965d87-e9c9-438e-8d8a-53c7f5d463db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[3]/div[@class=&quot;css-jza1fo&quot;]/div[1]/div[@class=&quot;css-5wh65g&quot;]/a[@class=&quot;Ui5-B4CDAk4Cv-cjLm4o0g== XeGJAOdlJaxl4+UD3zEJLg==&quot;]/div[@class=&quot;gG1uA844gIiB2+C3QWiaKA==&quot;]/div[@class=&quot;_2BUZ1gvKHeLMf12T+cRKig==&quot;]/div[@class=&quot;ODO+GeAyQ9sdtJOCc1-faA==&quot;]/div[@class=&quot;APPQ2hp9jN8+Z5v7YRNGbw== responsive lKpZCmwW6pa5aDKlZEpG8A==&quot;]/img[@class=&quot;H078hzBk9mrpZdtHF5MqWA== wSt-NCwsL186UdS6D-IpAg==&quot;]</value>
      <webElementGuid>564a0c9c-7bfc-462f-8e2e-fb5545b4afbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[3]/div/div/div/a/div/div/div/div/img</value>
      <webElementGuid>dd9dce26-c443-4ef3-be5b-9ed72fd22d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='product-image']</value>
      <webElementGuid>733ff109-aabc-411f-a541-e4166ffb5c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>b5481433-0217-486a-b799-7126cf1585b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'product-image' and @src = 'https://images.tokopedia.net/img/cache/200-square/VqbcmM/2023/1/20/93f7a13d-3a7e-402b-9377-ca38a56259c5.jpg.webp?ect=4g']</value>
      <webElementGuid>85801227-c4eb-418c-9a9b-7fc370265973</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
