<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_TENDA VILLAGE 13  GLAMPING  TENDA OTOMATIS NATUREHIKE CNH22ZP004</name>
   <tag></tag>
   <elementGuidId>aaa30ef7-3ee3-4c1b-96c1-edc3acd3924f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'TENDA VILLAGE 13 / GLAMPING / TENDA OTOMATIS NATUREHIKE CNH22ZP004' or . = 'TENDA VILLAGE 13 / GLAMPING / TENDA OTOMATIS NATUREHIKE CNH22ZP004')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.css-j63za0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>851ebfc0-d36e-4794-a4a4-efe23beb8ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f9348b3b-2e82-4186-baf5-030b8c5afd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-j63za0</value>
      <webElementGuid>8ea9b580-d660-4c0e-ac90-0aeb7d6fcaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lblPDPDetailProductName</value>
      <webElementGuid>9d784321-e2a2-4fb3-997c-7ee7049db338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TENDA VILLAGE 13 / GLAMPING / TENDA OTOMATIS NATUREHIKE CNH22ZP004</value>
      <webElementGuid>ef4e8985-0dbd-4feb-8b8a-b0df5713ff47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-product_content&quot;)/div[@class=&quot;css-jmbq56&quot;]/div[@class=&quot;css-1nylpq2&quot;]/h1[@class=&quot;css-j63za0&quot;]</value>
      <webElementGuid>b46ec816-1a98-4e15-ad75-4b309c78b344</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      <webElementGuid>827bf872-78ea-42fc-ba0a-b089a5c8c057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::h1[1]</value>
      <webElementGuid>0f2edc51-d851-4033-a449-8acd371cb401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/following::h1[1]</value>
      <webElementGuid>ab51db7a-bce1-4a7a-847b-df43301ab9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terjual'])[1]/preceding::h1[1]</value>
      <webElementGuid>a8c385d7-9f82-438a-b632-941af33408d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bintang'])[1]/preceding::h1[1]</value>
      <webElementGuid>75e909eb-8db8-43b8-a8bb-25c3f3309404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>31c1068e-05b0-4c17-a2e0-df8b63aad600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'TENDA VILLAGE 13 / GLAMPING / TENDA OTOMATIS NATUREHIKE CNH22ZP004' or . = 'TENDA VILLAGE 13 / GLAMPING / TENDA OTOMATIS NATUREHIKE CNH22ZP004')]</value>
      <webElementGuid>f836fb57-4e1d-4164-955a-368267fdf5fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
