<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kategori</name>
   <tag></tag>
   <elementGuidId>99abc6b5-cc46-4685-a2a3-ff967d958ff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.css-14acrss</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/main/section/div/div[2]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cdb4f89f-3963-4cfc-95d5-d99c50d8f299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.tokopedia.com/p?nref=chead&amp;source=homepage.dynamic_icon.0.824</value>
      <webElementGuid>a5d02867-8cf2-43df-a0f3-b8f9df007961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-14acrss</value>
      <webElementGuid>58ce748e-d301-49b3-a451-e5f4d617987c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c542609d-7978-4b53-b4e6-feeb6e19c2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fcb30bf9-2c02-4516-b746-29a9816134dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>icnHomeDynamicIcon#1</value>
      <webElementGuid>98c409b6-dac0-468f-ad1c-269b35631c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori</value>
      <webElementGuid>5511afdb-71c5-4b24-a646-7ec639671a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/main[@class=&quot;css-15x0u31&quot;]/section[@class=&quot;css-stopwq bordered&quot;]/div[@class=&quot;css-ut16ia&quot;]/div[@class=&quot;css-1ukamyt&quot;]/div[@class=&quot;css-1cysb4j&quot;]/div[@class=&quot;css-1jke4yk&quot;]/div[@class=&quot;css-1995st&quot;]/a[@class=&quot;css-14acrss&quot;]</value>
      <webElementGuid>466d5b70-7ba5-4176-ba76-4a81374b31c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/main/section/div/div[2]/div/div/div/a</value>
      <webElementGuid>32690936-f432-4951-8faf-83e7ea2bea0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli'])[1]/following::a[1]</value>
      <webElementGuid>19c5c678-728a-40a1-969b-b252f75a5914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nominal'])[1]/following::a[1]</value>
      <webElementGuid>9f6e0535-5236-4b5c-89e7-35d8162f31d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Handphone &amp; Tablet'])[1]/preceding::a[1]</value>
      <webElementGuid>76d0c14c-5c22-43ad-acb0-c2a577d49d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.tokopedia.com/p?nref=chead&amp;source=homepage.dynamic_icon.0.824')]</value>
      <webElementGuid>d8388bb8-b0c8-457b-a4bc-65a33cd78525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>0ab0b722-5fd0-44a3-a904-87289898df26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.tokopedia.com/p?nref=chead&amp;source=homepage.dynamic_icon.0.824' and (text() = 'Kategori' or . = 'Kategori')]</value>
      <webElementGuid>f5458bd2-2d8a-412b-a06d-5ade1b020f3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
