<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DJI Osmo Pocket 3 - Pocket Gimbal Camera - Pocket 3</name>
   <tag></tag>
   <elementGuidId>bb2da33e-cdaa-4c3d-a318-a5673dd9b1df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'DJI Osmo Pocket 3 - Pocket Gimbal Camera - Pocket 3' or . = 'DJI Osmo Pocket 3 - Pocket Gimbal Camera - Pocket 3')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.css-j63za0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>3db93605-8018-4f60-a218-5281cef4969b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5dc4b328-3427-4cd6-a1e2-ac37a6878816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-j63za0</value>
      <webElementGuid>26eb27f2-3823-42c3-a571-c029139ed3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lblPDPDetailProductName</value>
      <webElementGuid>754194f4-699b-4e84-a9cc-f615033ee5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DJI Osmo Pocket 3 - Pocket Gimbal Camera - Pocket 3</value>
      <webElementGuid>46e49f99-d47c-45ed-8dc0-c6ed6d4b7ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-product_content&quot;)/div[@class=&quot;css-jmbq56&quot;]/div[@class=&quot;css-1nylpq2&quot;]/h1[@class=&quot;css-j63za0&quot;]</value>
      <webElementGuid>f482063a-f8cb-432c-8972-def9f8109a30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      <webElementGuid>04b385b7-ce59-4573-80a4-d7bb7ade4046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::h1[1]</value>
      <webElementGuid>53e04aad-3636-49db-851c-926729e7a00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/following::h1[1]</value>
      <webElementGuid>799284e4-cf86-4aab-ab96-a940eeb33a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terjual'])[1]/preceding::h1[1]</value>
      <webElementGuid>48c5f21e-b8df-4ea1-878f-f19fb9b6d2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bintang'])[1]/preceding::h1[1]</value>
      <webElementGuid>653eaaff-8754-4ebd-a964-77a39bfefe3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>235b5660-c927-40f8-a7d4-ba6fb74acaec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'DJI Osmo Pocket 3 - Pocket Gimbal Camera - Pocket 3' or . = 'DJI Osmo Pocket 3 - Pocket Gimbal Camera - Pocket 3')]</value>
      <webElementGuid>6163c8e1-607e-4fea-915d-b81f68c5e493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
